[package]
name = "esos"
version = "0.1.0"
authors = ["FireCubez <firecubeez@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.14"
memmap = "0.7"
lru = "0.7"
